<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI3jmocy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI3jmocy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerI3jmocy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerI3jmocy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerI3jmocy\appDevDebugProjectContainer([
    'container.build_hash' => 'I3jmocy',
    'container.build_id' => '561463f9',
    'container.build_time' => 1582126362,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI3jmocy');
