<?php

namespace cantineFrontBundle\Repository;

/**
 * inscritionEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class inscritionEmailRepository extends \Doctrine\ORM\EntityRepository
{
}
