<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNdld8mb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNdld8mb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNdld8mb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNdld8mb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNdld8mb\appDevDebugProjectContainer([
    'container.build_hash' => 'Ndld8mb',
    'container.build_id' => '8f435818',
    'container.build_time' => 1582129049,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNdld8mb');
