user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

club:
    resource: "@ClubBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation
login:
    path:     /login