gestion:
    resource: "@GestionBundle/Resources/config/routing.yml"
    prefix:   /

scolarite:
    resource: "@ScolariteBundle/Resources/config/routing.yml"
    prefix:   /

cour:
    resource: "@CourBundle/Resources/config/routing.yml"
    prefix:   /

cantine_front:
    resource: "@cantineFrontBundle/Resources/config/routing.yml"
    prefix:   /

cantine:
    resource: "@cantineBundle/Resources/config/routing.yml"
    prefix:   /

club:
    resource: "@ClubBundle/Resources/config/routing.yml"
    prefix:   /


ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"

events:
    resource: "@EventsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

