<?php

namespace CourBundle\Controller;

use CourBundle\Entity\Panier;
use CourBundle\Entity\serie;
use CourBundle\Form\serieType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;

class SerieController extends Controller
{

    public function listAction()
    {
        $se=$this->getDoctrine()
            ->getRepository(serie::class)->findAll();

        return $this->render('@Cour/serie/listserie.html.twig',array('se'=>$se));
    }
    public function ajoutAction(Request $request)
    {
        $se = new serie();
        $form = $this->createForm(serieType::class, $se);
        $form->handleRequest($request);
        if ($form->isSubmitted())
        {  $brochureFile = $form->get('lien')->getData();
            if ($brochureFile) {
                $originalFilename = pathinfo($brochureFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $this->generateUniqueFileName();
                $newFilename = $safeFilename.'-'.uniqid().'.'.$brochureFile->guessExtension();
                try {
                    $brochureFile->move(
                        $this->getParameter('brochures_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                }
                $se->setLien($newFilename);

            }
            $em = $this->getDoctrine()->getManager();
            $em->persist($se);
            $em->flush();
            return $this->redirectToRoute("serie_list");
        }
        return $this->render('@Cour/serie/ajoutserie.html.twig',array('form'=>$form->createView()));
    }
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
    public function modifierAction(Request $request,$id)
    {
        $em=$this->getDoctrine()->getManager();
        $serie=$em->getRepository(serie::class)->find($id);

        if($request->isMethod('POST'))
        {
            $serie->setLien($request->get('lien'));
            $serie->setNomserie($request->get('nomserie'));
            $serie->setDescription($request->get('description'));

            $em->persist($serie);
            $em->flush();
            return $this->redirectToRoute("serie_list");
        }
        return $this->render('@Cour/serie/modifierserie.html.twig',array('serie'=>$serie));
    }
    public function supprimerAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $serie= $em->getRepository(serie::class)->find($id);//recuperation de avis a supp
        $em->remove($serie);
        $em->flush();//supp
        return $this->redirectToRoute("serie_list");
    }
    public function listafficheAction()
    {
        $se=$this->getDoctrine()
            ->getRepository(serie::class)->findAll();
        return $this->render('@Cour/seriefront/listseriefront.html.twig',array('se'=>$se));
    }
    Public function addToPanierAction(serie $serie)
    {
       $user    =   $this->getUser();  //hethi traja3lek eluser connecté
        if($user!=null)
        {
            $panier =   $user->getPanier();    // hethi lpanier mta3 luser connecté
            if($panier === null)
            {
                $panier =   new Panier();
                $panier->setEleve($user);
                $panier->addSerie($serie);
                $serie->addPanier($panier);
                $this->getDoctrine()->getManager()->persist($panier);
                $this->getDoctrine()->getManager()->flush();
                //hethi bech ken ma3andouch panier ya3mel wahda jdida w yajouti elserie
            }
            else
            {
                $panier->addSerie($serie);
                $serie->addPanier($panier);
                $this->getDoctrine()->getManager()->flush();
                //hethi mta3 ken 3andou
            }
        }
        return $this->redirectToRoute('serie_listfront');

    }
    public function paniebackAction()
    {
        $panier=$this->getDoctrine()
            ->getRepository(Panier::class)->findAll();
        return $this->render('@Cour/seriefront/listseriefront.html.twig',array('se'=>$panier));
    }


}
