<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.redirect_after_registration_subscriber' shared autowired service.

include_once $this->targetDirs[3].'\\src\\MainBundle\\EventListener\\RedirectAfterRegistrationSubscriber.php';

return $this->services['app.redirect_after_registration_subscriber'] = new \MainBundle\EventListener\RedirectAfterRegistrationSubscriber(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
