gestion_index1:
    path:     /gestion
    defaults: { _controller: GestionBundle:Default:index1 }

gestion_afficheC:
    path: /admin/afficheC
    defaults: { _controller: GestionBundle:Classe:afficheC }


gestion_afficheCfront:
    path: /afficheCfront
    defaults: { _controller: GestionBundle:Classe:afficheCfront }


Consulter_archive:
    path:     /admin/Affichage_Archive
    defaults: { _controller: GestionBundle:Reclamation:show_Admin_Archive }

statistique_reclamation:
    path: /admin/statistique_reclamation
    defaults: { _controller: GestionBundle:Reclamation:statistique_reclamation }

gestion_ajouterC:
    path: /admin/ajouterC
    defaults: { _controller: GestionBundle:Classe:ajouterC }

gestion_modifierC:
    path: /modifierC/{id}
    defaults: { _controller: GestionBundle:Classe:modifierC }

gestion_deleteC:
    path: /deleteC/{id}
    defaults: { _controller: GestionBundle:Classe:deleteC }

gestion_afficheR:
    path: /afficheR
    defaults: { _controller: GestionBundle:Reclamation:afficheR }

gestion_afficheRfront:
    path: /afficheRfront
    defaults: { _controller: GestionBundle:Reclamation:afficheRfront }

gestion_ajouterR:
    path: /ajouterR
    defaults: { _controller: GestionBundle:Reclamation:ajouterR }

gestion_modifierR:
    path: /modifierR
    defaults: { _controller: GestionBundle:Reclamation:modifierR }

gestion_deleteR:
    path: /deleteR/{id}
    defaults: { _controller: GestionBundle:Reclamation:deleteR }

gestion_deleteRfront:
    path: /deleteRfront/{id}
    defaults: { _controller: GestionBundle:Reclamation:deleteRfront }


gestion_archiverR:
    path: /archiverR/{id}
    defaults: { _controller: GestionBundle:Reclamation:archiverR }

gestion_afficherAR:
    path: /afficherAR
    defaults: { _controller: GestionBundle:Archive:index }

traiter_reclamation:
  path:     /admin/adminTraiter_Réclamation/{id}
  defaults: { _controller: GestionBundle:Reclamation:admin_traiter_reclamation }

score_update:
    path:     /admin/{id}/score_update
    defaults: { _controller: GestionBundle:Reclamation:update_score }
    requirements: { _method: post|put }

