<?php

namespace ReclamationBundle\Repository;
use AppBundle\Entity\User;
use ReclamationBundle\Entity\Reclamation;


/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public  function rechercheName($name){

        $dqlresult=$this->getEntityManager()
            ->createQuery("SELECT n FROM AppBundle:User n WHERE n.username=:username ")
            ->setParameter('username',$name);
        return $dqlresult->getResult();

    }




    public function recherchearchive1()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('COUNT(e)')
            ->from('ReclamationBundle:Reclamation', 'e')
            ->where("e.etat != 'Archivée' ");


        return $queryBuilder->getQuery()->getSingleScalarResult();
    }


    public function recherchearchive11($id)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('COUNT(e)')
            ->from('ReclamationBundle:Reclamation', 'e')
            ->where(("e.etat != 'Archivée' and e.user = $id") );


        return $queryBuilder->getQuery()->getSingleScalarResult();
    }


    public function recherchearchive2()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('COUNT(e)')
            ->from('ReclamationBundle:Reclamation', 'e')
            ->where("e.etat = 'Archivée'");


        return $queryBuilder->getQuery()->getSingleScalarResult();
    }



    public  function rechercheService($service){

        $dqlresult=$this->getEntityManager()
            ->createQuery("SELECT n FROM AppBundle:User n WHERE n.titre=:service ")
            ->setParameter('service',$service);
        return $dqlresult->getResult();

    }

    public  function chercheroless(){

        $dqlresult=$this->getEntityManager()
            ->createQuery("SELECT n FROM AppBundle:User n WHERE u.roles LIKE :role "
                            )
            ->setParameter('role','%"ROLE_PREST"%');
        return $dqlresult->getResult();

    }


}
